services:
  - type: web
    name: smartportfolio-backend
    env: docker
    region: oregon
    plan: free
    rootDir: backend
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: ALPACA_API_KEY
        sync: false
      - key: ALPACA_SECRET_KEY
        sync: false
      - key: ALPACA_PAPER_API_KEY
        sync: false
      - key: ALPACA_PAPER_SECRET_KEY
        sync: false
      - key: PORT
        value: 8080 