services:
  - type: web
    name: smartportfolio-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /test
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: DATABASE_URL
        sync: false 