name: Deploy to GitHub Pages

# Trigger deployment to test environment configuration
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        run: |
          git clone https://${DEPLOY_TOKEN}@github.com/${GITHUB_REPOSITORY}.git .
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

      - name: Setup Node
        run: |
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs
          node --version
          npm --version

      - name: Build Frontend
        run: |
          cd frontend
          npm ci
          npm run build
        env:
          VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
          VITE_POLYGON_API_KEY: ${{ secrets.VITE_POLYGON_API_KEY }}
          VITE_ALPACA_API_KEY: ${{ secrets.VITE_ALPACA_API_KEY }}
          VITE_ALPACA_SECRET_KEY: ${{ secrets.VITE_ALPACA_SECRET_KEY }}

      - name: Prepare deployment
        run: |
          # Save the built files
          mv frontend/dist /tmp/dist
          
          # Create a fresh gh-pages branch
          git checkout --orphan gh-pages
          git rm -rf .
          
          # Copy the built files
          cp -r /tmp/dist/* .
          touch .nojekyll
          
          # Configure git and commit
          git add .
          git commit -m "Deploy to GitHub Pages"
          
          # Force push to gh-pages branch
          git push -f origin gh-pages 