name: Deploy to GitHub Pages

# Trigger deployment to test environment configuration
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Create and setup frontend
        run: |
          # Create frontend directory
          mkdir -p frontend
          cd frontend
          
          # Initialize a new Vue.js project
          npm init vite@latest . -- --template vue-ts
          npm install
          
          # Install additional dependencies
          npm install @headlessui/vue @heroicons/vue @tailwindcss/forms axios chart.js vue-chartjs @vueuse/core
          
          # Copy frontend files from repository
          cp -r $GITHUB_WORKSPACE/frontend/* ./ || true
          
          # Build the project
          npm run build
        env:
          VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
          VITE_POLYGON_API_KEY: ${{ secrets.VITE_POLYGON_API_KEY }}
          VITE_ALPACA_API_KEY: ${{ secrets.VITE_ALPACA_API_KEY }}
          VITE_ALPACA_SECRET_KEY: ${{ secrets.VITE_ALPACA_SECRET_KEY }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist
          force_orphan: true 