name: Deploy to GitHub Pages

# Trigger deployment to test environment configuration
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        run: |
          # Create and move to a clean directory
          mkdir -p /tmp/build
          cd /tmp/build
          
          # Clone the repository
          git clone https://${DEPLOY_TOKEN}@github.com/${GITHUB_REPOSITORY}.git .
          
          # Verify clone was successful
          if [ ! -d "frontend" ]; then
            echo "Error: frontend directory not found after clone"
            exit 1
          fi
          
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

      - name: Setup Node
        working-directory: /tmp/build
        run: |
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs
          node --version
          npm --version

      - name: Build Frontend
        working-directory: /tmp/build/frontend
        run: |
          npm ci
          npm run build
        env:
          VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
          VITE_POLYGON_API_KEY: ${{ secrets.VITE_POLYGON_API_KEY }}
          VITE_ALPACA_API_KEY: ${{ secrets.VITE_ALPACA_API_KEY }}
          VITE_ALPACA_SECRET_KEY: ${{ secrets.VITE_ALPACA_SECRET_KEY }}

      - name: Deploy
        working-directory: /tmp/build
        run: |
          # Create a fresh gh-pages branch
          git checkout --orphan gh-pages
          git rm -rf .
          
          # Copy the built files
          cp -r frontend/dist/* .
          touch .nojekyll
          
          # Configure git and commit
          git add .
          git commit -m "Deploy to GitHub Pages"
          
          # Force push to gh-pages branch
          git push -f origin gh-pages 