name: Deploy to GitHub Pages

# Trigger deployment to test environment configuration
on:
  push:
    branches:
      - master

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          git clone https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git .
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node
        run: |
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs

      - name: Build
        working-directory: frontend
        env:
          VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
          VITE_POLYGON_API_KEY: ${{ secrets.VITE_POLYGON_API_KEY }}
          VITE_ALPACA_API_KEY: ${{ secrets.VITE_ALPACA_API_KEY }}
          VITE_ALPACA_SECRET_KEY: ${{ secrets.VITE_ALPACA_SECRET_KEY }}
        run: |
          npm ci
          npm run build

      - name: Deploy
        run: |
          git checkout --orphan gh-pages
          git rm -rf .
          cp -r frontend/dist/* .
          touch .nojekyll
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -f origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 